export interface SchemaField {
  name: string;
  type: 'Numeric' | 'Alphanumeric' | 'Date';
  length: number;
}

export interface ReportSchema {
  id: string;
  name: string;
  description: string;
  fields: SchemaField[];
  recordTypeCode?: string; // Optional filter for record types (e.g., '05', '10')
  tcrCode?: string;        // Optional filter for TCR sequence number (e.g., '0', '1')
  group?: string;          // Optional group for consolidating multiple TCRs
}

export const REPORT_SCHEMAS: ReportSchema[] = [
  {
    id: 'IP727010-AA',
    name: 'Clearing Cycle Acknowledgment Report',
    description: 'Details transactions sent from customers to Mastercard (Mastercard-settled, Bilateral, Global Collection Only, and Non-Financial transactions).',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Run Date', type: 'Date', length: 8 },
      { name: 'Page No', type: 'Numeric', length: 8 },
      { name: 'Acceptance Brand', type: 'Alphanumeric', length: 3 },
      { name: 'Business Service Level', type: 'Alphanumeric', length: 20 },
      { name: 'Business Service ID', type: 'Numeric', length: 6 },
      { name: 'File ID', type: 'Alphanumeric', length: 25 },
      { name: 'Member ID', type: 'Numeric', length: 11 },
      { name: 'Settlement Indicator', type: 'Alphanumeric', length: 20 },
      { name: 'Trans. Func.', type: 'Numeric', length: 7 },
      { name: 'Proc. Code', type: 'Numeric', length: 6 },
      { name: 'IRD', type: 'Alphanumeric', length: 2 },
      { name: 'Counts', type: 'Numeric', length: 12 },
      { name: 'Recon Amount', type: 'Numeric', length: 18 },
      { name: 'Recon Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Trans Fee', type: 'Numeric', length: 18 },
      { name: 'Fee Curr Code', type: 'Alphanumeric', length: 3 },
      { name: 'Total / Subtotal', type: 'Numeric', length: 18 },
    ],
  },
  {
    id: 'IP727020-AA',
    name: 'Clearing Cycle Notification Report',
    description: 'Details transactions sent from Mastercard to customers (Mastercard-settled, Bilateral, and Non-Financial transactions).',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Run Date', type: 'Date', length: 8 },
      { name: 'Page', type: 'Numeric', length: 8 },
      { name: 'Acceptance Brand', type: 'Alphanumeric', length: 3 },
      { name: 'Business Service Level', type: 'Alphanumeric', length: 20 },
      { name: 'Business Service ID', type: 'Numeric', length: 6 },
      { name: 'File ID', type: 'Alphanumeric', length: 25 },
      { name: 'Member ID', type: 'Numeric', length: 11 },
      { name: 'Settlement Indicator', type: 'Alphanumeric', length: 20 },
      { name: 'Trans. Func.', type: 'Numeric', length: 7 },
      { name: 'Proc. Code', type: 'Numeric', length: 6 },
      { name: 'IRD', type: 'Alphanumeric', length: 2 },
      { name: 'Counts', type: 'Numeric', length: 12 },
      { name: 'Recon. Amount', type: 'Numeric', length: 18 },
      { name: 'Recon. Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Trans. Fee', type: 'Numeric', length: 18 },
      { name: 'Fee Curr. Code', type: 'Alphanumeric', length: 3 },
      { name: 'Total', type: 'Numeric', length: 18 },
      { name: 'Subtotal', type: 'Numeric', length: 18 },
    ],
  },
  {
    id: 'IP728010-AA',
    name: 'Clearing Cycle Summary Reconciliation Report',
    description: 'A summary by each clearing cycle by each clearing member ID of clearing cycle activity.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Run Date', type: 'Date', length: 8 },
      { name: 'Page', type: 'Numeric', length: 8 },
      { name: 'Acceptance Brand', type: 'Alphanumeric', length: 3 },
      { name: 'Business Service Level', type: 'Alphanumeric', length: 20 },
      { name: 'Business Service ID', type: 'Numeric', length: 6 },
      { name: 'Member ID', type: 'Numeric', length: 11 },
      { name: 'Cycle Activity', type: 'Numeric', length: 2 },
      { name: 'File ID To Mastercard', type: 'Alphanumeric', length: 25 },
      { name: 'File ID From Mastercard', type: 'Alphanumeric', length: 25 },
      { name: 'Net Reconciliation Currency Amount', type: 'Numeric', length: 18 },
      { name: 'Reconciliation Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Clearing Day Total As Of Clearing (001-006)', type: 'Numeric', length: 18 },
    ],
  },
  {
    id: 'IP142110-AA',
    name: 'IPM Messages Created on Behalf of a Member',
    description: 'Details Fee Collection/1740 messages created by Mastercard on behalf of the customer.',
    fields: [
      { name: 'Record Type (D)', type: 'Alphanumeric', length: 1 },
      { name: 'Transaction Originator Institution ID Code', type: 'Numeric', length: 11 },
      { name: 'MTI', type: 'Numeric', length: 4 },
      { name: 'Function Code', type: 'Numeric', length: 3 },
      { name: 'Message Reason Code', type: 'Numeric', length: 4 },
      { name: 'File ID', type: 'Numeric', length: 25 },
      { name: 'CR DR Indicator', type: 'Alphanumeric', length: 2 },
      { name: 'Central Site Processing Date of Original Message', type: 'Date', length: 6 },
      { name: 'Transaction Type', type: 'Alphanumeric', length: 2 },
      { name: 'Processing Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Amount', type: 'Numeric', length: 12 },
      { name: 'Transaction Currency Code', type: 'Numeric', length: 3 },
      { name: 'Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Reconciliation Amount', type: 'Numeric', length: 12 },
      { name: 'Reconciliation Currency Code', type: 'Numeric', length: 3 },
      { name: 'Reconciliation Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Transaction Destination Institution ID Code', type: 'Numeric', length: 11 },
      { name: 'Forwarding Institution ID Code', type: 'Numeric', length: 11 },
      { name: 'Fee Collection Control Number', type: 'Numeric', length: 20 },
      { name: 'Card Program Identifier', type: 'Alphanumeric', length: 3 },
      { name: 'Receiving Institution ID Code', type: 'Numeric', length: 11 },
      { name: 'MasterCom Control Number', type: 'Alphanumeric', length: 7 },
      { name: 'PAN', type: 'Alphanumeric', length: 19 },
    ],
  },
  {
    id: 'IP148320-AA',
    name: 'Miscellaneous Override Financial Adjustments Report',
    description: 'Details of Clearing System generated Fee Collection records for message reason code 7808 by BIN/Acct Range.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Member ID', type: 'Alphanumeric', length: 11 },
      { name: 'FEE-ADJ-SETTLE-SERVICE', type: 'Alphanumeric', length: 10 },
      { name: 'FEE-ADJ-ACCT-RANGE', type: 'Alphanumeric', length: 38 },
      { name: 'FEE-ADJ-CURR-CD', type: 'Alphanumeric', length: 3 },
      { name: 'FEE-ADJ-CURR-EXP', type: 'Alphanumeric', length: 1 },
      { name: 'FEE-TRX-CURR-CD', type: 'Alphanumeric', length: 3 },
      { name: 'FEE-TRX-CURR-EXP', type: 'Alphanumeric', length: 1 },
      { name: 'FEE-ADJ-ALIGN-EXP', type: 'Alphanumeric', length: 1 },
      { name: 'FEE-ADJ-AMOUNT-DR', type: 'Numeric', length: 18 },
      { name: 'FEE-ADJ-AMOUNT-CR', type: 'Numeric', length: 18 },
      { name: 'FEE-ADJ-AMOUNT-NET', type: 'Numeric', length: 18 },
      { name: 'FEE-ADJ-NET-DR-CR', type: 'Alphanumeric', length: 2 },
      { name: 'FEE-TRX-AMOUNT-DR', type: 'Numeric', length: 18 },
      { name: 'FEE-TRX-AMOUNT-CR', type: 'Numeric', length: 18 },
      { name: 'FEE-TRX-AMOUNT-NET', type: 'Numeric', length: 18 },
      { name: 'FEE-TRX-NET-DR-CR', type: 'Alphanumeric', length: 2 },
    ],
  },
  {
    id: 'IP755140-AA',
    name: 'Clearing Interchange Enhancement Reconciliation Report',
    description: 'Specific details of clearing messages in which the acquirer provided IRD in PDS 0158 subfield 4 is different than the IRD derived by the clearing system.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Distribution ICA', type: 'Numeric', length: 11 },
      { name: 'Amount, Transaction', type: 'Numeric', length: 12 },
      { name: 'Amount, Reconciliation', type: 'Numeric', length: 12 },
      { name: 'Date and Time, Local Transaction', type: 'Numeric', length: 12 },
      { name: 'Acquirer Reference Data', type: 'Numeric', length: 23 },
      { name: 'File ID', type: 'Alphanumeric', length: 25 },
      { name: 'Amount Fee Reconciliation', type: 'Numeric', length: 12 },
      { name: 'Extended: Interchange Amount, Fee, Recon', type: 'Numeric', length: 18 },
      { name: 'Card Program Identifier', type: 'Alphanumeric', length: 3 },
      { name: 'Business Service Arrangement Type Code', type: 'Numeric', length: 1 },
      { name: 'Business Service ID Code', type: 'Alphanumeric', length: 6 },
      { name: 'IRD submitted by the acquirer', type: 'Alphanumeric', length: 2 },
      { name: 'Enriched IRD', type: 'Alphanumeric', length: 2 },
      { name: 'Currency Code, Transaction', type: 'Numeric', length: 3 },
      { name: 'Currency Code, Reconciliation', type: 'Numeric', length: 3 },
      { name: 'Trace ID', type: 'Alphanumeric', length: 15 },
      { name: 'Transaction Link ID', type: 'Alphanumeric', length: 22 },
    ],
  },
  {
    id: 'IP755220-AA',
    name: 'Account Level Management (ALM) Reconciliation Data Report',
    description: 'Offered to acquirers to use with the Interchange Detail Report and Clearing Detail Report to facilitate reconciliation for ALM transactions.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Distribution ICA', type: 'Numeric', length: 11 },
      { name: 'MTI', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 19 },
      { name: 'Transaction Amount', type: 'Numeric', length: 12 },
      { name: 'Recon Amount', type: 'Numeric', length: 12 },
      { name: 'Function Code', type: 'Numeric', length: 3 },
      { name: 'Acquirer Ref Data', type: 'Numeric', length: 23 },
      { name: 'Transaction Currency', type: 'Numeric', length: 3 },
      { name: 'Recon Currency', type: 'Numeric', length: 3 },
      { name: 'Trace ID', type: 'Alphanumeric', length: 15 },
      { name: 'GCMS Product ID', type: 'Alphanumeric', length: 3 },
      { name: 'Licensed Product ID', type: 'Alphanumeric', length: 3 },
      { name: 'Transaction Fee Amount', type: 'Numeric', length: 36 },
      { name: 'Extended Precision Amount', type: 'Numeric', length: 48 },
      { name: 'Central Site Busn Date', type: 'Numeric', length: 6 },
      { name: 'ALM Service Data', type: 'Alphanumeric', length: 15 },
      { name: 'Additional Fee Amounts', type: 'Alphanumeric', length: 384 },
      { name: 'Processing Code', type: 'Numeric', length: 2 },
      { name: 'Acceptor Business Code (MCC)', type: 'Numeric', length: 4 },
      { name: 'Approval Code', type: 'Alphanumeric', length: 6 },
      { name: 'Acceptor ID', type: 'Alphanumeric', length: 15 },
      { name: 'Transaction Originator ICA', type: 'Numeric', length: 11 },
      { name: 'File ID', type: 'Alphanumeric', length: 25 },
      { name: 'Acquirer Submitted IRD', type: 'Alphanumeric', length: 2 },
      { name: 'Mastercard Interchange Derivation Service Derived IRD', type: 'Alphanumeric', length: 2 },
      { name: 'Reversal Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Mastercard Assigned ID (MAID)', type: 'Alphanumeric', length: 6 },
      { name: 'ALM Service Data Related to Mastercard One Credential', type: 'Alphanumeric', length: 23 },
      { name: 'Mastercard One Credential Exclusion Indicator', type: 'Alphanumeric', length: 1 },
    ],
  },
  {
    id: 'IP857010-BB',
    name: 'Global Collection Only Error Detail - Input Sequence',
    description: 'Details of rejected Global Collection Only transactions.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Run Date', type: 'Date', length: 8 },
      { name: 'Page', type: 'Numeric', length: 8 },
      { name: 'File ID', type: 'Alphanumeric', length: 25 },
      { name: 'Processing Mode', type: 'Alphanumeric', length: 20 },
      { name: 'Description', type: 'Alphanumeric', length: 100 },
      { name: 'Source Message Number', type: 'Numeric', length: 8 },
      { name: 'Source Amount', type: 'Numeric', length: 18 },
      { name: 'MTI: Function Code', type: 'Alphanumeric', length: 10 },
      { name: 'Source Currency', type: 'Alphanumeric', length: 3 },
      { name: 'Error Code', type: 'Alphanumeric', length: 10 },
      { name: 'Error Description', type: 'Alphanumeric', length: 100 },
      { name: 'Source Element ID', type: 'Alphanumeric', length: 10 },
      { name: 'Invalid Data', type: 'Alphanumeric', length: 100 },
      { name: 'Message Details', type: 'Alphanumeric', length: 100 },
      { name: 'Message Type', type: 'Alphanumeric', length: 20 },
      { name: 'Financial Detail', type: 'Numeric', length: 12 },
      { name: 'Non-Financial Detail', type: 'Numeric', length: 12 },
      { name: 'Unrecognizable Detail', type: 'Numeric', length: 12 },
      { name: 'Currency', type: 'Alphanumeric', length: 3 },
      { name: 'Amount', type: 'Numeric', length: 18 },
      { name: 'Count', type: 'Numeric', length: 12 },
    ],
  },
  {
    id: 'IP857010-AA',
    name: 'Error Detail - Input Sequence',
    description: 'Provides all Data Elements of a rejected message highlighting the DE in error.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Run Date', type: 'Date', length: 8 },
      { name: 'Page', type: 'Numeric', length: 8 },
      { name: 'File ID', type: 'Alphanumeric', length: 25 },
      { name: 'Processing Mode', type: 'Alphanumeric', length: 20 },
      { name: 'Error Code', type: 'Alphanumeric', length: 10 },
      { name: 'Description', type: 'Alphanumeric', length: 100 },
      { name: 'Source Message Number', type: 'Numeric', length: 8 },
      { name: 'Element ID', type: 'Alphanumeric', length: 10 },
      { name: 'Invalid Data', type: 'Alphanumeric', length: 100 },
      { name: 'File Information', type: 'Alphanumeric', length: 100 },
      { name: 'Message Level: Source Message Number', type: 'Numeric', length: 8 },
      { name: 'Message Level: Source Amount', type: 'Numeric', length: 18 },
      { name: 'Message Level: MTI-Function Code', type: 'Alphanumeric', length: 10 },
      { name: 'Message Level: Source Currency', type: 'Alphanumeric', length: 3 },
      { name: 'Message Level: Error Code', type: 'Alphanumeric', length: 10 },
      { name: 'Message Level: Description', type: 'Alphanumeric', length: 100 },
      { name: 'Message Level: Element ID', type: 'Alphanumeric', length: 10 },
      { name: 'Message Level: Invalid Data', type: 'Alphanumeric', length: 100 },
      { name: 'Message Level: Message Details', type: 'Alphanumeric', length: 100 },
      { name: 'Summary: Message Type', type: 'Alphanumeric', length: 20 },
      { name: 'Summary: Financial Detail', type: 'Numeric', length: 12 },
      { name: 'Summary: Non-Financial Detail', type: 'Numeric', length: 12 },
      { name: 'Summary: Unrecognizable Detail', type: 'Numeric', length: 12 },
      { name: 'Summary: Currency', type: 'Alphanumeric', length: 3 },
      { name: 'Summary: Amount', type: 'Numeric', length: 18 },
      { name: 'Summary: Count', type: 'Numeric', length: 12 },
    ],
  },
  {
    id: 'IP776010-AA',
    name: 'Transaction/Chargeback Analysis Report',
    description: 'Life Cycle Volume Analysis for Acquirers/Issuers.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Report Name', type: 'Alphanumeric', length: 100 },
      { name: 'Report Number', type: 'Alphanumeric', length: 20 },
      { name: 'Customer ID', type: 'Numeric', length: 11 },
      { name: 'Customer Name', type: 'Alphanumeric', length: 100 },
      { name: 'Report Subtitle', type: 'Alphanumeric', length: 100 },
      { name: 'Run Date', type: 'Date', length: 8 },
      { name: 'Page', type: 'Numeric', length: 8 },
      { name: 'Period From', type: 'Date', length: 17 },
      { name: 'Year-to-date', type: 'Date', length: 4 },
      { name: 'Financial Detail Sent', type: 'Numeric', length: 12 },
      { name: 'Dollar Volume', type: 'Numeric', length: 18 },
      { name: 'First Chargeback Received', type: 'Numeric', length: 12 },
      { name: 'Chargeback Dollars', type: 'Numeric', length: 18 },
      { name: 'Retrieval Reqst Recd', type: 'Numeric', length: 12 },
      { name: 'PCNT FNCL', type: 'Numeric', length: 5 },
      { name: 'PCNT Global Clearing Management System', type: 'Numeric', length: 5 },
      { name: 'Retrieval Volume Sent', type: 'Numeric', length: 12 },
      { name: 'Retrieval Volume Fulfillments Sent', type: 'Numeric', length: 12 },
      { name: 'Retrieval Volume CgbkRecd', type: 'Numeric', length: 12 },
      { name: 'vs Retvls Recd', type: 'Numeric', length: 5 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'Retrieval Volume Retrvls Recd vs Fin Sent', type: 'Numeric', length: 5 },
      { name: '1st Cgbk', type: 'Numeric', length: 12 },
      { name: '2nd Pres', type: 'Numeric', length: 12 },
      { name: 'Arbitration Chargeback', type: 'Numeric', length: 12 },
      { name: 'Total Volume', type: 'Numeric', length: 12 },
      { name: 'Total', type: 'Numeric', length: 12 },
      { name: 'Average Ticket', type: 'Numeric', length: 18 },
    ],
  },
  {
    id: 'IP776020-AA',
    name: 'Chargeback Activity Summary: Acquirer',
    description: 'Summarizes chargeback activity by reason code.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Report Name', type: 'Alphanumeric', length: 100 },
      { name: 'Report Number', type: 'Alphanumeric', length: 20 },
      { name: 'Customer ID', type: 'Numeric', length: 11 },
      { name: 'Customer Name', type: 'Alphanumeric', length: 100 },
      { name: 'Report Subtitle', type: 'Alphanumeric', length: 100 },
      { name: 'Run Date', type: 'Date', length: 8 },
      { name: 'Page', type: 'Numeric', length: 8 },
      { name: 'Period From', type: 'Date', length: 17 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'Percent of Cgbk', type: 'Numeric', length: 5 },
      { name: 'Total Cgbk Volume', type: 'Numeric', length: 12 },
      { name: 'Total Cgbk DollarAmount', type: 'Numeric', length: 18 },
      { name: '1st Cgbk', type: 'Numeric', length: 12 },
      { name: '2nd Pres', type: 'Numeric', length: 12 },
      { name: 'Arb Cgbk', type: 'Numeric', length: 12 },
      { name: 'Grand Total', type: 'Numeric', length: 12 },
    ],
  },
  {
    id: 'IP776030-AA',
    name: 'Dollar/Volume Summary Report: Acquirer',
    description: 'Summarizes dollar and transaction volume for acquirers.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Transactions', type: 'Numeric', length: 12 },
      { name: 'Dollar Amount', type: 'Numeric', length: 18 },
      { name: 'Financial Detail Debits', type: 'Numeric', length: 18 },
      { name: 'Financial Detail Debit Reversals', type: 'Numeric', length: 18 },
      { name: 'Financial Detail Credits', type: 'Numeric', length: 18 },
      { name: 'Financial Detail Credit Reversals', type: 'Numeric', length: 18 },
      { name: 'Net Total (Transactions)', type: 'Numeric', length: 12 },
      { name: 'Net Total (Dollar Volume)', type: 'Numeric', length: 18 },
      { name: 'Chargeback Debits / Reversals', type: 'Numeric', length: 18 },
      { name: 'Chargeback Credits / Reversals', type: 'Numeric', length: 18 },
      { name: 'Representment Debits / Reversals', type: 'Numeric', length: 18 },
      { name: 'Representment Credits / Reversals', type: 'Numeric', length: 18 },
      { name: 'Retrieval Requests / Reversals', type: 'Numeric', length: 12 },
      { name: 'Retrieval Request Fulfillments / Reversals', type: 'Numeric', length: 12 },
    ],
  },
  {
    id: 'IP170010-AA',
    name: 'Acquirer-funded Reward Presentments Created On Behalf of a Customer Report',
    description: 'Aids acquirers in reconciling promotions that are merchant-funded.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'TRAN-ORIG', type: 'Alphanumeric', length: 11 },
      { name: 'FILE-ID', type: 'Alphanumeric', length: 25 },
      { name: 'ACCEPTOR', type: 'Alphanumeric', length: 15 },
      { name: 'REWARD-PGM', type: 'Alphanumeric', length: 11 },
      { name: 'MTI', type: 'Alphanumeric', length: 4 },
      { name: 'FUNC-CD', type: 'Alphanumeric', length: 3 },
      { name: 'PROC-CD', type: 'Alphanumeric', length: 2 },
      { name: 'TRAN-AMT', type: 'Numeric', length: 12 },
      { name: 'TRAN-CR-DR-IND', type: 'Alphanumeric', length: 2 },
      { name: 'TRAN-CUR', type: 'Alphanumeric', length: 3 },
      { name: 'RECON-AMT', type: 'Numeric', length: 12 },
      { name: 'RECON-CR-DR-IND', type: 'Alphanumeric', length: 2 },
      { name: 'FEE-IN-RECON-CUR', type: 'Numeric', length: 12 },
      { name: 'FEE-IN-RECON-CR-DR-IND', type: 'Alphanumeric', length: 2 },
      { name: 'FEE-IN-CALC-CUR', type: 'Numeric', length: 12 },
      { name: 'FEE-CALC-CUR', type: 'Alphanumeric', length: 3 },
      { name: 'FEE-IN-CALC-CR-DR-IND', type: 'Alphanumeric', length: 2 },
      { name: 'RECON-CUR', type: 'Alphanumeric', length: 3 },
      { name: 'TRAN-DEST', type: 'Alphanumeric', length: 11 },
      { name: 'CARD-PGM-ID', type: 'Alphanumeric', length: 3 },
    ],
  },
  {
    id: 'IP830010',
    name: 'Issuer ICCR Report',
    description: 'For issuers participating in the Issuer Currency Conversation Rate (ICCR) service.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'ICA', type: 'Alphanumeric', length: 11 },
      { name: 'MTI Code', type: 'Alphanumeric', length: 4 },
      { name: 'Function Code', type: 'Alphanumeric', length: 3 },
      { name: 'Processing Date', type: 'Alphanumeric', length: 8 },
      { name: 'PAN', type: 'Alphanumeric', length: 19 },
      { name: 'Process Code', type: 'Numeric', length: 2 },
      { name: 'Issuer ICA', type: 'Numeric', length: 11 },
      { name: 'Reversal Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Filler 1', type: 'Alphanumeric', length: 3 },
      { name: 'Transaction Date', type: 'Alphanumeric', length: 6 },
      { name: 'Transaction Time', type: 'Alphanumeric', length: 4 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Banknet Reference Number', type: 'Alphanumeric', length: 9 },
      { name: 'Transaction Amount', type: 'Numeric', length: 12 },
      { name: 'Transaction Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Transaction Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Reconciliation Amount', type: 'Numeric', length: 12 },
      { name: 'Reconciliation Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Reconciliation Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Cardholder Billing Amount', type: 'Alphanumeric', length: 12 },
      { name: 'Cardholder Billing Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Cardholder Billing Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Filler 2', type: 'Alphanumeric', length: 8 },
      { name: 'ICCR Amount', type: 'Numeric', length: 12 },
      { name: 'ICCR Rate', type: 'Numeric', length: 15 },
    ],
  },
  {
    id: 'IP830020',
    name: 'Cross-Border Fee Manager service reports',
    description: 'For issuers participating in the Cross-Border Fee Manager service.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'ICA', type: 'Alphanumeric', length: 11 },
      { name: 'MTI Code', type: 'Alphanumeric', length: 4 },
      { name: 'Function Code', type: 'Alphanumeric', length: 3 },
      { name: 'Processing Date', type: 'Alphanumeric', length: 8 },
      { name: 'Primary Account Number', type: 'Alphanumeric', length: 19 },
      { name: 'Process Code', type: 'Numeric', length: 2 },
      { name: 'Issuer ICA', type: 'Numeric', length: 11 },
      { name: 'Reversal Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Filler 1', type: 'Alphanumeric', length: 3 },
      { name: 'Transaction Date', type: 'Alphanumeric', length: 6 },
      { name: 'Transaction Time', type: 'Alphanumeric', length: 4 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Banknet Reference Number', type: 'Alphanumeric', length: 9 },
      { name: 'Transaction Amount', type: 'Numeric', length: 12 },
      { name: 'Transaction Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Transaction Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Reconciliation Amount', type: 'Numeric', length: 12 },
      { name: 'Reconciliation Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Reconciliation Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Cardholder Billing Amount', type: 'Alphanumeric', length: 12 },
      { name: 'Cardholder Billing Currency Code', type: 'Alphanumeric', length: 3 },
      { name: 'Cardholder Billing Currency Exponent', type: 'Alphanumeric', length: 1 },
      { name: 'Filler 2', type: 'Alphanumeric', length: 8 },
      { name: 'Currency Conversion Method Amount (% Rate)', type: 'Numeric', length: 12 },
      { name: 'Currency Conversion Method % Rate', type: 'Numeric', length: 15 },
      { name: 'Currency Conversion Method Amount (Fixed Rate)', type: 'Numeric', length: 12 },
      { name: 'Currency Conversion Method Fixed Rate', type: 'Numeric', length: 12 },
      { name: 'Cross-Border Flex Method Amount (% Rate)', type: 'Numeric', length: 12 },
      { name: 'Cross-Border Flex Method % Rate', type: 'Numeric', length: 15 },
      { name: 'Cross-Border Flex Method Amount (Fixed Rate)', type: 'Numeric', length: 12 },
      { name: 'Cross Border Flex Method Fixed Rate', type: 'Numeric', length: 12 },
      { name: 'Cross-Border Cost Method Amount (% Rate)', type: 'Numeric', length: 12 },
      { name: 'Cross-Border Cost Method % Rate', type: 'Numeric', length: 15 },
    ],
  },
  {
    id: 'IP755020-AA',
    name: 'Interchange Detail Report',
    description: 'Offered to acquirers in the Europe region and South Africa to comply with regulatory requirements regarding their fees.',
    fields: [
      { name: 'Record Type', type: 'Alphanumeric', length: 1 },
      { name: 'Acquirer ICA', type: 'Numeric', length: 11 },
      { name: 'MTI', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 19 },
      { name: 'Processing Code', type: 'Numeric', length: 6 },
      { name: 'Amount Transaction', type: 'Numeric', length: 12 },
      { name: 'Reconciliation Amount', type: 'Numeric', length: 12 },
      { name: 'Date and Time Local Transaction', type: 'Numeric', length: 12 },
      { name: 'Point of Service Data Code', type: 'Alphanumeric', length: 12 },
      { name: 'Function Code', type: 'Numeric', length: 3 },
      { name: 'Message Reason Code', type: 'Numeric', length: 4 },
      { name: 'Acceptor Business Code', type: 'Numeric', length: 4 },
      { name: 'Acquirer Reference Data', type: 'Numeric', length: 23 },
      { name: 'Approval Code', type: 'Alphanumeric', length: 6 },
      { name: 'Service Code', type: 'Numeric', length: 3 },
      { name: 'Acceptor Terminal ID', type: 'Alphanumeric', length: 8 },
      { name: 'Acceptor ID Code', type: 'Alphanumeric', length: 15 },
      { name: 'Acceptor Name and Location', type: 'Alphanumeric', length: 83 },
      { name: 'Acceptor Post Code', type: 'Alphanumeric', length: 10 },
      { name: 'Global Clearing Management System Product Identifier', type: 'Alphanumeric', length: 3 },
      { name: 'Licensed Product Identifier', type: 'Alphanumeric', length: 3 },
      { name: 'Terminal Type', type: 'Alphanumeric', length: 3 },
      { name: 'Message Reversal Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Electronic Commerce Security Level Indicator', type: 'Alphanumeric', length: 3 },
      { name: 'File ID: File Reference Date', type: 'Numeric', length: 6 },
      { name: 'Fee Type Code', type: 'Numeric', length: 2 },
      { name: 'Fee Processing Code', type: 'Numeric', length: 2 },
      { name: 'Fee Settlement Indicator', type: 'Numeric', length: 2 },
      { name: 'Currency Code', type: 'Numeric', length: 3 },
      { name: 'Amounts Transaction Fee', type: 'Numeric', length: 12 },
      { name: 'Currency Code Fee Reconciliation', type: 'Numeric', length: 3 },
      { name: 'Amount Fee Reconciliation', type: 'Numeric', length: 12 },
      { name: 'Extended: Fee Type Code', type: 'Numeric', length: 2 },
      { name: 'Extended: Fee Processing Code', type: 'Numeric', length: 2 },
      { name: 'Extended: Fee Settlement indicator', type: 'Numeric', length: 2 },
      { name: 'Extended: Currency Code, Fee', type: 'Numeric', length: 3 },
      { name: 'Extended: Interchange Amount, Fee', type: 'Numeric', length: 18 },
      { name: 'Extended: Currency Code, Fee, Recon.', type: 'Numeric', length: 3 },
      { name: 'Extended: Interchange Amount, Fee, Recon.', type: 'Numeric', length: 18 },
      { name: 'Currency Exponents', type: 'Numeric', length: 4 },
      { name: 'Card Program Identifier', type: 'Alphanumeric', length: 3 },
      { name: 'Business Service Arrangement Type Code', type: 'Numeric', length: 1 },
      { name: 'Business Service ID Code', type: 'Alphanumeric', length: 6 },
      { name: 'Interchange Rate Designator', type: 'Alphanumeric', length: 2 },
      { name: 'Central Site Business Date', type: 'Numeric', length: 6 },
      { name: 'Business Cycle', type: 'Numeric', length: 2 },
      { name: 'Acceptor Classification Override Ind.', type: 'Alphanumeric', length: 1 },
      { name: 'Product Class Override Indicator', type: 'Alphanumeric', length: 3 },
      { name: 'Corporate Incentive Rates Apply Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Special Conditions Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Mastercard Assigned ID Override Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'ALM Account Category Code', type: 'Alphanumeric', length: 1 },
      { name: 'Rate Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'MasterPass Incentive Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Settlement Service Transfer Agent ID', type: 'Alphanumeric', length: 11 },
      { name: 'Settlement Service Transfer Agent Account', type: 'Alphanumeric', length: 28 },
      { name: 'Settlement Service Level Code', type: 'Numeric', length: 1 },
      { name: 'Settlement Service ID Code', type: 'Alphanumeric', length: 10 },
      { name: 'Settlement Foreign Exchange Rate Class Code', type: 'Alphanumeric', length: 1 },
      { name: 'Reconciliation Date', type: 'Numeric', length: 6 },
      { name: 'Reconciliation Cycle', type: 'Numeric', length: 2 },
      { name: 'Settlement Date', type: 'Numeric', length: 6 },
      { name: 'Settlement Cycle', type: 'Numeric', length: 2 },
      { name: 'Transaction Currency Code', type: 'Numeric', length: 3 },
      { name: 'Reconciliation Currency Code', type: 'Numeric', length: 3 },
      { name: 'Additional Amount', type: 'Alphanumeric', length: 20 },
      { name: 'Trace ID', type: 'Alphanumeric', length: 15 },
      { name: 'Digital Wallet Interchange Override Indicator', type: 'Alphanumeric', length: 1 },
    ],
  },
];
