import { ReportSchema } from "./schemas";

export const VISA_REPORT_SCHEMAS: ReportSchema[] = [
  {
    id: 'TC05-TCR0',
    name: 'TC05 TCR0 - Sales Draft (Financial)',
    description: 'Primary financial record for Sales Drafts.',
    recordTypeCode: '05',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'PAN Extension', type: 'Numeric', length: 3 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Acquirer Business ID', type: 'Alphanumeric', length: 8 },
      { name: 'Purchase Date', type: 'Date', length: 4 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Merchant Name', type: 'Alphanumeric', length: 25 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Merchant Category Code', type: 'Numeric', length: 4 },
      { name: 'Merchant State/Province Code', type: 'Alphanumeric', length: 2 },
      { name: 'Merchant Zip Code', type: 'Alphanumeric', length: 5 },
      { name: 'Authorization Code', type: 'Alphanumeric', length: 6 },
      { name: 'POS Entry Mode', type: 'Numeric', length: 2 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
      { name: 'Reimbursement Attribute', type: 'Alphanumeric', length: 1 },
    ],
  },
  {
    id: 'TC05-TCR1',
    name: 'TC05 TCR1 - Sales Draft (Merchant Info)',
    description: 'Additional merchant and transaction information for Sales Drafts.',
    recordTypeCode: '05',
    tcrCode: '1',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Merchant Address', type: 'Alphanumeric', length: 38 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant State/Province', type: 'Alphanumeric', length: 2 },
      { name: 'Merchant Zip Code', type: 'Alphanumeric', length: 9 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Merchant Telephone', type: 'Alphanumeric', length: 14 },
      { name: 'Merchant ID', type: 'Alphanumeric', length: 15 },
      { name: 'Filler', type: 'Alphanumeric', length: 70 },
    ],
  },
  {
    id: 'TC06-TCR0',
    name: 'TC06 TCR0 - Credit Voucher (Financial)',
    description: 'Primary financial record for Credit Vouchers.',
    recordTypeCode: '06',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'PAN Extension', type: 'Numeric', length: 3 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Acquirer Business ID', type: 'Alphanumeric', length: 8 },
      { name: 'Purchase Date', type: 'Date', length: 4 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Merchant Name', type: 'Alphanumeric', length: 25 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Merchant Category Code', type: 'Numeric', length: 4 },
      { name: 'Merchant State/Province Code', type: 'Alphanumeric', length: 2 },
      { name: 'Merchant Zip Code', type: 'Alphanumeric', length: 5 },
      { name: 'Authorization Code', type: 'Alphanumeric', length: 6 },
      { name: 'POS Entry Mode', type: 'Numeric', length: 2 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
      { name: 'Reimbursement Attribute', type: 'Alphanumeric', length: 1 },
    ],
  },
  {
    id: 'TC10-TCR0',
    name: 'TC10 TCR0 - Fee Collection',
    description: 'Primary record for Fee Collection and Funds Transfer.',
    recordTypeCode: '10',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Message Text', type: 'Alphanumeric', length: 70 },
      { name: 'Settlement Flag', type: 'Alphanumeric', length: 1 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
  {
    id: 'TC15-TCR0',
    name: 'TC15 TCR0 - Chargeback (Financial)',
    description: 'Primary financial record for Chargebacks.',
    recordTypeCode: '15',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Chargeback Reference Number', type: 'Alphanumeric', length: 6 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
  {
    id: 'TC20-TCR0',
    name: 'TC20 TCR0 - Representment (Financial)',
    description: 'Primary financial record for Representments.',
    recordTypeCode: '20',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Representment Reference Number', type: 'Alphanumeric', length: 6 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
  {
    id: 'TC33-TCR0',
    name: 'TC33 TCR0 - Clearing Detail',
    description: 'General detail record for TC33 clearing files.',
    recordTypeCode: '33',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Merchant Name', type: 'Alphanumeric', length: 25 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Authorization Code', type: 'Alphanumeric', length: 6 },
      { name: 'POS Entry Mode', type: 'Numeric', length: 2 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
];
