import { ReportSchema } from "./schemas";

export const VISA_REPORT_SCHEMAS: ReportSchema[] = [
  {
    id: 'TC05-TCR0',
    name: 'TC05 TCR0 - Sales Draft (Financial)',
    group: 'TC05',
    description: 'Primary financial record for Sales Drafts.',
    recordTypeCode: '05',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'PAN Extension', type: 'Numeric', length: 3 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Acquirer Business ID', type: 'Alphanumeric', length: 8 },
      { name: 'Purchase Date', type: 'Date', length: 4 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Merchant Name', type: 'Alphanumeric', length: 25 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Merchant Category Code', type: 'Numeric', length: 4 },
      { name: 'Merchant State/Province Code', type: 'Alphanumeric', length: 2 },
      { name: 'Merchant Zip Code', type: 'Alphanumeric', length: 5 },
      { name: 'Authorization Code', type: 'Alphanumeric', length: 6 },
      { name: 'POS Entry Mode', type: 'Numeric', length: 2 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
      { name: 'Reimbursement Attribute', type: 'Alphanumeric', length: 1 },
    ],
  },
  {
    id: 'TC05-TCR1',
    name: 'TC05 TCR1 - Sales Draft (Merchant Info)',
    group: 'TC05',
    description: 'Additional merchant and transaction information for Sales Drafts.',
    recordTypeCode: '05',
    tcrCode: '1',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Merchant Address', type: 'Alphanumeric', length: 38 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant State/Province', type: 'Alphanumeric', length: 2 },
      { name: 'Merchant Zip Code', type: 'Alphanumeric', length: 9 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Merchant Telephone', type: 'Alphanumeric', length: 14 },
      { name: 'Merchant ID', type: 'Alphanumeric', length: 15 },
      { name: 'Filler', type: 'Alphanumeric', length: 70 },
    ],
  },
  {
    id: 'TC06-TCR0',
    name: 'TC06 TCR0 - Credit Voucher (Financial)',
    group: 'TC06',
    description: 'Primary financial record for Credit Vouchers.',
    recordTypeCode: '06',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'PAN Extension', type: 'Numeric', length: 3 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Acquirer Business ID', type: 'Alphanumeric', length: 8 },
      { name: 'Purchase Date', type: 'Date', length: 4 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Merchant Name', type: 'Alphanumeric', length: 25 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Merchant Category Code', type: 'Numeric', length: 4 },
      { name: 'Merchant State/Province Code', type: 'Alphanumeric', length: 2 },
      { name: 'Merchant Zip Code', type: 'Alphanumeric', length: 5 },
      { name: 'Authorization Code', type: 'Alphanumeric', length: 6 },
      { name: 'POS Entry Mode', type: 'Numeric', length: 2 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
      { name: 'Reimbursement Attribute', type: 'Alphanumeric', length: 1 },
    ],
  },
  {
    id: 'TC10-TCR0',
    name: 'TC10 TCR0 - Fee Collection',
    description: 'Primary record for Fee Collection and Funds Transfer.',
    recordTypeCode: '10',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Message Text', type: 'Alphanumeric', length: 70 },
      { name: 'Settlement Flag', type: 'Alphanumeric', length: 1 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
  {
    id: 'TC15-TCR0',
    name: 'TC15 TCR0 - Chargeback (Financial)',
    description: 'Primary financial record for Chargebacks.',
    recordTypeCode: '15',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Chargeback Reference Number', type: 'Alphanumeric', length: 6 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
  {
    id: 'TC20-TCR0',
    name: 'TC20 TCR0 - Representment (Financial)',
    description: 'Primary financial record for Representments.',
    recordTypeCode: '20',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Representment Reference Number', type: 'Alphanumeric', length: 6 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
  {
    id: 'TC33-TCR0',
    name: 'TC33 TCR0 - Clearing Detail',
    group: 'TC33',
    description: 'General detail record for TC33 clearing files.',
    recordTypeCode: '33',
    tcrCode: '0',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Destination BIN', type: 'Numeric', length: 6 },
      { name: 'Source BIN', type: 'Numeric', length: 6 },
      { name: 'Reason Code', type: 'Numeric', length: 4 },
      { name: 'PAN', type: 'Alphanumeric', length: 16 },
      { name: 'Acquirer Reference Number', type: 'Alphanumeric', length: 23 },
      { name: 'Destination Amount', type: 'Numeric', length: 12 },
      { name: 'Destination Currency Code', type: 'Numeric', length: 3 },
      { name: 'Source Amount', type: 'Numeric', length: 12 },
      { name: 'Source Currency Code', type: 'Numeric', length: 3 },
      { name: 'Merchant Name', type: 'Alphanumeric', length: 25 },
      { name: 'Merchant City', type: 'Alphanumeric', length: 13 },
      { name: 'Merchant Country Code', type: 'Alphanumeric', length: 3 },
      { name: 'Authorization Code', type: 'Alphanumeric', length: 6 },
      { name: 'POS Entry Mode', type: 'Numeric', length: 2 },
      { name: 'Central Processing Date', type: 'Date', length: 4 },
    ],
  },
  {
    id: 'TC33-TCR2',
    name: 'TC33 TCR2 - RDMS Detail',
    group: 'TC33',
    description: 'Raw Data Merchant Settlement (RDMS) detail record.',
    recordTypeCode: '33',
    tcrCode: '2',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Merchant ID', type: 'Alphanumeric', length: 15 },
      { name: 'Store Number', type: 'Alphanumeric', length: 10 },
      { name: 'Terminal ID', type: 'Alphanumeric', length: 8 },
      { name: 'Transaction Date', type: 'Date', length: 4 },
      { name: 'Transaction Time', type: 'Numeric', length: 6 },
      { name: 'Settlement Date', type: 'Date', length: 4 },
      { name: 'RDMS Control Number', type: 'Alphanumeric', length: 12 },
      { name: 'Merchant Outlet Name', type: 'Alphanumeric', length: 25 },
      { name: 'Filler', type: 'Alphanumeric', length: 80 },
    ],
  },
  {
    id: 'TC33-TCR3',
    name: 'TC33 TCR3 - Base II Dispute',
    group: 'TC33',
    description: 'Base II Dispute detailed record for TC33.',
    recordTypeCode: '33',
    tcrCode: '3',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Numeric', length: 1 },
      { name: 'Case Number', type: 'Alphanumeric', length: 12 },
      { name: 'Dispute Reason Code', type: 'Numeric', length: 4 },
      { name: 'Dispute Amount', type: 'Numeric', length: 12 },
      { name: 'Dispute Currency', type: 'Numeric', length: 3 },
      { name: 'Original ARN', type: 'Alphanumeric', length: 23 },
      { name: 'Documentation Indicator', type: 'Alphanumeric', length: 1 },
      { name: 'Member Message Text', type: 'Alphanumeric', length: 50 },
      { name: 'Filler', type: 'Alphanumeric', length: 55 },
    ],
  },
  {
    id: 'TC33-TCRA',
    name: 'TC33.A - Supplemental Data',
    group: 'TC33',
    description: 'Supplemental data record (TCR A) for TC33.',
    recordTypeCode: '33',
    tcrCode: 'A',
    fields: [
      { name: 'Transaction Code', type: 'Numeric', length: 2 },
      { name: 'Transaction Code Qualifier', type: 'Numeric', length: 1 },
      { name: 'Component Sequence Number', type: 'Alphanumeric', length: 1 },
      { name: 'Supplemental Data Type', type: 'Alphanumeric', length: 2 },
      { name: 'Data Content', type: 'Alphanumeric', length: 162 },
    ],
  },
];
